name: "Posten Levering"
description: "Levering av post annenhver dag. Henter de neste leveringene fra posten.no"
version: "2.0.2.1"
slug: "posten"
init: false
arch:
  - amd64
  - aarch64
# image: "ghcr.io/vegardbeider/posten-levering-{arch}-addon"
options:
  postnummer: ""
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""

schema:
  postnummer: str
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str