name: "Posten Levering"
description: "Levering av post annenhver dag. Henter de neste leveringene fra posten.no"
version: "1.3.2"
slug: "posten"
init: false
arch:
  - amd64
image: "vegardbeider/posten-levering"
options:
  postnummer: ""
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""

schema:
  postnummer: str
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str