name: "Tellstick MQTT"
description: "Bridge between Tellstick and MQTT"
version: "0.5.1.3"
slug: "tellstick-mqtt"
init: false
arch:
  - amd64
  - aarch64
# image: "ghcr.io/vegardbeider/tellstick-mqtt-ha-{arch}-addon"
options:
  mqtt_host: ""
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  telldus_repeat_cmd: 3

schema:
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  telldus_repeat_cmd: int
usb: true
map: 
  - addon_config