blueprint:
  name: MQTT 433 MHz Switches
  description: Read 433 MHz switches directly from MQTT
  domain: automation
  author: Vegard Jacobsen
  source_url: https://github.com/Vegardbeider/ha-addons/edit/main/tellstick-mqtt/mqtt-433-switches.yaml
  input:
    mqtt_device:
      name: MQTT device topic
      description: The topic of the MQTT device (telldus/<id>/switch/state)
      selector:
        text: {}
    action_on:
      name: Action ON
      selector:
        action: {}
    action_off:
      name: Action OFF
      selector:
        action: {}

trigger:
  - alias: Switch turned ON
    platform: mqtt
    topic: !input mqtt_device
    payload: "{\"switch\": 1}"
    id: switch_on
  - alias: Switch turned OFF
    platform: mqtt
    topic: !input mqtt_device
    payload: "{\"switch\": 2}"
    id: switch_off
action:
  - alias: "Turn on light"
    if:
      - condition: trigger
        id:
          - switch_on
    then:
      - sequence: !input action_on
  - alias: "Turn off light"
    if:
      - condition: trigger
        id:
          - switch_off
    then:
      - sequence: !input action_off
mode: single
